version: '3'
services:
  pg:
    image: postgres:9.6
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=goq
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=goq
