// DO NOT EDIT. This code is generated by Goq.
// https://github.com/ryym/goq

package tests

import (
	"github.com/ryym/goq"
	"github.com/ryym/goq/cllct"
	"github.com/ryym/goq/dialect"
	"github.com/ryym/goq/goql"
)

type Countries struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID   *goql.Column
	Name *goql.Column
}

func NewCountries(alias string) *Countries {
	cm := goql.NewColumnMaker("Country", "countries").As(alias)
	t := &Countries{

		ID:   cm.Col("ID", "id").PK().Bld(),
		Name: cm.Col("Name", "name").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name}
	t.Table = goql.NewTable("countries", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Countries) As(alias string) *Countries { return NewCountries(alias) }

type Cities struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID        *goql.Column
	Name      *goql.Column
	CountryID *goql.Column
}

func NewCities(alias string) *Cities {
	cm := goql.NewColumnMaker("City", "cities").As(alias)
	t := &Cities{

		ID:        cm.Col("ID", "id").PK().Bld(),
		Name:      cm.Col("Name", "name").Bld(),
		CountryID: cm.Col("CountryID", "country_id").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name, t.CountryID}
	t.Table = goql.NewTable("cities", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Cities) As(alias string) *Cities { return NewCities(alias) }

type Addresses struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID     *goql.Column
	Name   *goql.Column
	CityID *goql.Column
}

func NewAddresses(alias string) *Addresses {
	cm := goql.NewColumnMaker("Address", "addresses").As(alias)
	t := &Addresses{

		ID:     cm.Col("ID", "id").PK().Bld(),
		Name:   cm.Col("Name", "name").Bld(),
		CityID: cm.Col("CityID", "city_id").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name, t.CityID}
	t.Table = goql.NewTable("addresses", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Addresses) As(alias string) *Addresses { return NewAddresses(alias) }

type Techs struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID   *goql.Column
	Name *goql.Column
	Desc *goql.Column
}

func NewTechs(alias string) *Techs {
	cm := goql.NewColumnMaker("Tech", "technologies").As(alias)
	t := &Techs{

		ID:   cm.Col("ID", "id").PK().Bld(),
		Name: cm.Col("Name", "name").Bld(),
		Desc: cm.Col("Desc", "description").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name, t.Desc}
	t.Table = goql.NewTable("technologies", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Techs) As(alias string) *Techs { return NewTechs(alias) }

type Builder struct {
	*goq.Builder

	Countries *Countries
	Cities    *Cities
	Addresses *Addresses
	Techs     *Techs
}

func NewBuilder(dl dialect.Dialect) *Builder {
	return &Builder{
		Builder: goq.NewBuilder(dl),

		Countries: NewCountries(""),
		Cities:    NewCities(""),
		Addresses: NewAddresses(""),
		Techs:     NewTechs(""),
	}
}
