version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          POSTGRES_PORT: 5432
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: goq
          POSTGRES_DB: goq
    working_directory: /go/src/github.com/ryym/goq
    steps:
      - checkout
      - run: go test -v -race `go list ./... | grep -v /tests`
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Integration test
          # FIXME: Building `mattn/go-sqlite3` without `go install`ing it takes some time.
          # So skip SQLite3 tests on CI for now.
          # (https://groups.google.com/forum/#!topic/golang-nuts/KexEyiy6PvA)
          command: go test -v -race `ls ./tests/*.go | grep -v sqlite3_test.go`
