version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          POSTGRES_PORT: 5432
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: goq
          POSTGRES_DB: goq
    working_directory: /go/src/github.com/ryym/goq
    steps:
      - checkout
      - run: go test -race `go list ./... | grep -v /tests`
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Integration test
          command: go test -race ./tests
