// DO NOT EDIT. This code is generated by Goq.
// https://github.com/ryym/goq

package cllct_test

import (
	"github.com/ryym/goq"
	"github.com/ryym/goq/cllct"
	"github.com/ryym/goq/dialect"
	"github.com/ryym/goq/goql"
)

type Users struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID   *goql.Column
	Name *goql.Column
}

func NewUsers(alias string) *Users {
	cm := goql.NewColumnMaker("User", "users").As(alias)
	t := &Users{

		ID:   cm.Col("ID", "id").PK().Bld(),
		Name: cm.Col("Name", "name").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name}
	t.Table = goql.NewTable("users", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Users) As(alias string) *Users { return NewUsers(alias) }

type Countries struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID   *goql.Column
	Name *goql.Column
}

func NewCountries(alias string) *Countries {
	cm := goql.NewColumnMaker("Country", "countries").As(alias)
	t := &Countries{

		ID:   cm.Col("ID", "id").PK().Bld(),
		Name: cm.Col("Name", "name").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name}
	t.Table = goql.NewTable("countries", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Countries) As(alias string) *Countries { return NewCountries(alias) }

type Cities struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID        *goql.Column
	Name      *goql.Column
	CountryID *goql.Column
}

func NewCities(alias string) *Cities {
	cm := goql.NewColumnMaker("City", "cities").As(alias)
	t := &Cities{

		ID:        cm.Col("ID", "id").PK().Bld(),
		Name:      cm.Col("Name", "name").Bld(),
		CountryID: cm.Col("CountryID", "country_id").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Name, t.CountryID}
	t.Table = goql.NewTable("cities", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Cities) As(alias string) *Cities { return NewCities(alias) }

type Addresses struct {
	goql.Table
	*cllct.ModelCollectorMaker

	ID         *goql.Column
	Address1   *goql.Column
	Address2   *goql.Column
	CityID     *goql.Column
	PostalCode *goql.Column
}

func NewAddresses(alias string) *Addresses {
	cm := goql.NewColumnMaker("Address", "addresses").As(alias)
	t := &Addresses{

		ID:         cm.Col("ID", "id").PK().Bld(),
		Address1:   cm.Col("Address1", "address1").Bld(),
		Address2:   cm.Col("Address2", "address2").Bld(),
		CityID:     cm.Col("CityID", "city_id").Bld(),
		PostalCode: cm.Col("PostalCode", "postal_code").Bld(),
	}
	cols := []*goql.Column{t.ID, t.Address1, t.Address2, t.CityID, t.PostalCode}
	t.Table = goql.NewTable("addresses", alias, cols)
	t.ModelCollectorMaker = cllct.NewModelCollectorMaker(cols, alias)
	return t
}

func (t *Addresses) As(alias string) *Addresses { return NewAddresses(alias) }

type Builder struct {
	*goq.Builder

	Users     *Users
	Countries *Countries
	Cities    *Cities
	Addresses *Addresses
}

func NewBuilder(dl dialect.Dialect) *Builder {
	return &Builder{
		Builder: goq.NewBuilder(dl),

		Users:     NewUsers(""),
		Countries: NewCountries(""),
		Cities:    NewCities(""),
		Addresses: NewAddresses(""),
	}
}
